### ISSUE TITLE
[Chapter 1] 메소드 참조 코드 예시에 관한 질문

### ISSUE THREAD

**Issue by BUYA-GH** [UMC-PNU-3rd/modern-java-in-action#1]
## 출처
> p.53, 16번째 줄부터
> 
> 다음처럼 메서드를 호출할 수 있다.
> ```
> filterApples(inventory, Apple::isGreenApple);
> ```

## 질문
메소드 참조에서 사용된 코드에 예시에 질문사항이 있습니다. 

지금까지의 내용을 봤을 때 메소드 참조는 `{객체}::{객체의 메서드}` 의 형태였고
그 객체의 메서드를 참조한다는 의미로 이해했습니다.
그런데 p.52~p.53 에서의 코드 예시는 다르게 되어 있었습니다.

```
public static boolean isHeavyApple(Apple apple) {
    return apple.getWeight() > 150;
}

...

filterApples(inventory, Apple::isHeavyApple);
```

`isHeaveApple` 은 Apple 클래스 내에서 선언된 Apple의 메서드가 아닌,
Apple 객체를 Input으로 받는 메서드입니다.

만약 제 이해대로 라면 `isHeaveApple`는 Apple 클래스 내부에서 선언된 메소드여야
`Apple::isHeavyApple` 로 메소드 참조가 가능할 것 같습니다.

그렇다면 이 코드의 예시에서
Apple 클래스 내부에서 선언되었지만 그 부분을 생략해 표기한 것일까요?
아니면 그 객체를 입력으로 받는 메소드 또한 그 객체의 메소드 참조가 되는 것인가요?

**Comment by jk05018** [comment]
음 일단 저희가 용어에 대해서 서로 헷갈리는 부분이 있어서 용어부터 정리하고 가 볼게요!
메소드 참조는 `{객체}::{객체의 메서드}`의 형태라고 하셨습니다! 이 때 만약 객체가 `인스턴스`를 의미한다면 메서드 참조에 대해서 잘못 이해하신 것 같아요!!

메서드 참조는 `{클래스}::{클래스의 메서드}`의 형태로 이루어져 있으며 다음과 같은 클래스의 메서드를 사용할 수 있습니다.
1. 클래스의 정적(Static) 메서드
2. 클래스의 인스턴스(Instance) 메서드
3. 클래스의 생성자(Constructor)

즉 메서드 참조를 넘겨준다는 말은 그 “클래스”의 메서드를 파라미터(매개변수)로 넘겨줘서 사용할 수 있게 한다는 의미입니다!
(클래스와 객체(인스턴스)를 잘 구분하셔야 합니다! 중요해요!)
——

자 이제 질문으로 돌아와서 이야기해 보죠!
```
그렇다면 이 코드의 예시에서 Apple 클래스 내부에서 선언되었지만 그 부분을 생략해 표기한 것일까요? 
아니면 그 객체를 입력으로 받는 메소드 또한 그 객체의 메소드 참조가 되는 것인가요? 
```

이 질문에 대해서 저의 답변은
Q. Apple 클래스 내부에서 선언되었지만 그 부분을 생략해 표기한 것일까요?
A.
1. 메서드 참조에 사용되는 메서드는 Apple 클래스 내부에 선언되어 있습니다. 맨 위 참조!
2. Apple의 isHeavyApple를 filterApples 메서드의 파라미터(Predicate)로 넘겨준 것입니다.
3. 따라서 filterApples 메서드 내에서 isHeavyApple을 사용할 수 있습니다( Predicate -> p.test로 사용)

어느 부분에서 이해가 되지 않으시는지 잘 알겠습니다! 하지만 이 부분에 대해서는 함수형 인터페이스, 람다의 동작 방식을 이해해야 이해하실 수 있을 것 같아요!
일단 이정도로 이해하고 나신 뒤 2,3장을 학습하시고 다시 돌아와 보시면 좋을 것 같습니다~

Q. 그 객체를 입력으로 받는 메소드 또한 그 객체의 메소드 참조가 되는 것인가요? 
A.
isHeavyApple은 Apple 클래스의 정적(Static) 메서드입니다. 따라서 메서드 참조를 통해 메서드를 넘겨줄 수 있습니다.

53p에 보시면 아래의 코드가 보이실 겁니다!
```
  if(p.test(apple){
	  …
  }
```

저희가 Predicate 메서드(isHeavyApple)을 넘겨줬었죠!
p.test(apple)을 실행하면 Apple.isHeavyApple(apple)이 실행됩니다!

이 부분 역시 뒤에 함수형 인터페이스와 람다에 대해서 학습해보시면 어떤 의미인지 알게 되실 것 같습니다.

결론이 뒤에서 배운다!로 끝나서 매우 죄송스럽긴 하네요:) 이해가 부족하신 부분에 대해서는 추후 목요일날 직접 만나서 자세하게 설명드릴게요!

**Comment by BUYA-GH** [comment]
설명 감사드립니다.
책에 다시 보니 실습 코드를 다운받아 볼 수 있다길래 제가 받아서 코드를 확인 해봤습니다.

그런데 책이랑 실습 코드의 내용이 다르더라고요?

책에서는 
```
filterApples(inventory, Apple::isGreenApple);
filterApples(inventory, Apple::isHeavyApple);
```
라고 되어 있었지만, 다운 받아 보는 실습 코드에서는

![화면 캡처 2022-09-28 185853](https://user-images.githubusercontent.com/64539267/192750400-d5eeb1f8-325d-46c4-8909-7998b2e8974b.png)
위 처럼 `isGreenApple`이나 `isHeavyApple` 이 Apple 클래스의 메소드가 아니라
FilteringApples의 메소드로 정의되어 있네요.

이 부분은 스터디 도중에 연결해서 공유하겠습니다.
책이랑 실습 코드가 다른 부분이 있는거 같네요.
