### ISSUE TITLE
[Chapter 1] 코드 파라미터화와 병렬성

### ISSUE THREAD

**Issue by Ji-Hyeon212** [UMC-PNU-3rd/modern-java-in-action#2]
## 출처
> p.54, 마지막 줄(부터)
> filterApples(inventory, (Apple a) -> a.getWeight() > 150 );
하지만 다음처럼 라이브러리 메서드 filter를 이용하면 filterApples 메서드를 구현할 필요가 없다.
filter(inventory, (Apple a) -> a.getWeight() > 150);
하지만 병렬성이라는 중요성 때문에 설계자들은 이와 같은 설계를 포기했다.

## 질문
'병렬성'이라는 중요성 때문에 포기했다는 것의 의미를 잘 모르겠습니다.

**Comment by shkisme** [comment]
저도 비슷한 질문이 생겨서 여기에 이슈를 남깁니다!!!

해당 메서드는 `Collection`의 `filter` 메서드입니다.

p. 56을 보면, 다음과 같이 나와있습니다.

> `컬렉션`에서는 반복 과정을 `for each`문을 이용한 직접 처리를 했다. 이러한 방식을 `외부 반복`이라고 한다. 반면 `스트림 API` 를 이용하면 라이브러리 내부에서 모든 데이터가 처리된다. 이와 같은 반복을 `내부 반복`이라고 한다.
> 

또한 p. 45를 보면, (둘째 단락)

> `스트림 API`를 사용하면, `스레드`라는 복잡한 작업을 사용하지 않으면서도 공짜로 `병렬성`을 얻을 수 있다.
> 

라고 나와있습니다.

아마도 여기서 말하는 “병렬성이라는 중요성 때문에” 는 `Collection`을 사용했기 때문에 병렬성 처리에 어려움이 있었던 것 같습니다.

## 질문

1. 여기서 말하는 `병렬성`이 정확히 어떤 의미인가요? 여러 스레드에서 동시에 처리하는… 느낌인 것인가요?
2. 스트림의 `내부 반복`이 어떤 과정이길래 병렬성 이슈를 해결했나요? 이 부분은 뒷 부분에 나오나요?

**Comment by jk05018** [comment]
Q. '병렬성'이라는 중요성 때문에 포기했다는 것의 의미를 잘 모르겠습니다.

지현님! 이 부분에 대해서는 글로 적기 힘들것 같아서 이따 말로 의견 교류해 보겠습니다!

**Comment by jk05018** [comment]
질문
Q. 여기서 말하는 병렬성이 정확히 어떤 의미인가요? 여러 스레드에서 동시에 처리하는… 느낌인 것인가요?
A. 
맞습니다. 멀티코어 CPU를 활용하기 위해서 여러 스레드에서 동시에 처리해 줍니다.
기존의 Java8 이전에는 syncronized인지 뭐시기를 써서 개발자가 전부 처리해야했지만 
스트림 API를 제공함으로써 병렬성 관리를 컴퓨터에 위임합니다!

Q. 스트림의 내부 반복이 어떤 과정이길래 병렬성 이슈를 해결했나요? 이 부분은 뒷 부분에 나오나요?
스트림의 내부 반복은 58p에 나온대로 동작할 겁니다! 이 부분을 이해하신다면 병렬성도 쉽게 이해하실 것 같아요!
