### ISSUE TITLE
[Chapter 2] 동작 파라미터화에 관한 질문

### ISSUE THREAD

**Issue by shkisme** [UMC-PNU-3rd/modern-java-in-action#3]
## 출처
> p. 75 
> 컬렉션 탐색 로직과 각 항목에 적용할 동작을 분리할 수 있다는 것이 **동작 파라미터화**의 강점이다.

## 질문
해당 페이지까지 책을 읽고, `동작 파라미터`라는 것이 정말 유용하다는 것을 새롭게 알게되었습니다! 

```java
public static List<Apple> filterApples(List<Apple> inventory, ApplePredicate p){
	List<Apple> result = new ArrayList<>();
	for(Apple apple: inventory){
		if(p.test(apple)){
			result.add(apple);
		}
	}
	return result;
}
```
위 코드를 보면 인자로 `ApplePredicate p` 를 넘겨주고 있습니다. 여기서도 마찬가지로 `객체`를 넘겨주는 것이 아니라 `클래스`를 넘겨주고 있는 것인가요? 제가 제대로 이해한 것이 맞을까요?

**Comment by jk05018** [comment]
Q. 위 코드를 보면 인자로 ApplePredicate p 를 넘겨주고 있습니다. 여기서도 마찬가지로 객체를 넘겨주는 것이 아니라 클래스를 넘겨주고 있는 것인가요? 제가 제대로 이해한 것이 맞을까요?

일단 먼저
1. 함수형 인터페이스 -> 익명 클래스 -> 람다 -> 메서드 참조
2. 다형성
에 대해서 잘 이해하고 계셔야 할 것 같아요! (물론 잘 이해하신다고 믿고 있습니다~)

질문을 제가 잘 이해한 것인지 모르겠지만
원래 메서드 시그니처에서는 클래스를 명시하고 메서드를 호출할 때 객체를 넘겨줘요!
- 시그니처(signature) = 반환타입(Return value) + 메서드명(Method name) + 매개변수(Parameters)

## 예시
```java
// 예시
List<Apple> addApple(Apple apple){ // 클래스 명시
    ....
}

일단메서드명.addApple(new Apple(...)); // 객체를 넘겨줌

```

위에서도 마찬가지로 메서드 파라미터는 함수형 인터페이스 ApplePredicate(클래스)를 명시한 뒤
메서드를 호출할 때 객체를 넘겨주는 방식으로 동작합니다!

```java
public static List<Apple> filterApples(List<Apple> inventory, ApplePredicate p){
    ...
}

List<Apple> inventory = new ArrayList<>();

List<Apple> heavyApples = filterApples(inventory, new APpleHeavyWeightPredicate());
```

설명이 아직 부족할 거라 생각합니다! 이따 얘기해 보도록 하죠!
