### ISSUE TITLE
[Chapter 3] Object o가 람다식을 받을 수 있는 이유에 대한 질문

### ISSUE THREAD

**Issue by BUYA-GH** [UMC-PNU-3rd/modern-java-in-action#5]
## 출처
> p.111, 퀴즈 3-5에서
> 람다 표현식을 명시적으로 대상 형식을 제공하는 Runnalbe로 캐스팅해서 문제를 해결할 수도 있다.
> ```java
> Object o = (Runnable) () -> { System.out.println("Tricky example"); };
> ```

## 질문
Object는 함수형 인터페이스가 아니기 때문에
```java
Object o = () -> { System.out.println("Tricky example"); };
```
위와 같은 코드에서는 오류가 난다고 들었습니다.

이를 해결 하기 위해 `출처` 처럼 Runnable로 캐스팅 후 람다식을 넘겨주면 된다고 했는데,

함수형 인터페이스가 아닌 Object에 람다식을 넘기면 어떤 일이 일어나는지 알고 싶습니다.

추가적으로 `() -> void` 형식의 함수 디스크립터를 갖는 Runnable로 캐스팅하면 해결되는 이유도 궁금합니다.

**Comment by shkisme** [comment]
1. **함수형 인터페이스가 아닌 Object에 람다식을 넘기면 어떤 일이 일어나는지**
람다식의 대상 형식은 `인터페이스`이어야 할 것입니다. 하지만 Object는 함수형 인터페이스가 아니라, 총 11개의 메서드로 구성된 `클래스`(최상위 클래스) 입니다. 따라서 `컴파일 에러`가 발생할 것입니다!

2. **`() -> void` 형식의 함수 디스크립터를 갖는 Runnable로 캐스팅하면 해결되는 이유**
void 형식의 함수 디스크립터를 갖는 Runnable로 대상 형식을 바꿔서 문제를 해결한 것 같습니다.
아래 코드와 같은 과정일 것 같습니다.
```java
Runnable r = () -> {
      System.out.println("Tricky example");
}; 
// 람다식의 대상 형식은 Runnable<T> 이다.
// Runnable<T> 의 추상 메서드는 인수는 없고 void를 반환하는 run()메서드이다.
// 함수 디스크립터는 () -> void 이므로 람다의 시그니처와 일치한다.
Object o = r; // Object 클래스는 최상위 클래스 이므로, 대입이 가능하다.
```

답변 내용 중 혹시 제가 잘못 이해한 부분이 있다면 말씀해주세요!!

**Comment by BUYA-GH** [comment]
아 Object가 최상위 클래스였다는 사실을 까먹었네요. 감사합니다!!
