### ISSUE TITLE
[Chapter 3] 람다 지역 변수 사용에서 final을 제한 하지 않는 이유

### ISSUE THREAD

**Issue by BUYA-GH** [UMC-PNU-3rd/modern-java-in-action#7]
## 출처
> p.113, 5번째 줄부터
> 하지만 그러려면 지역 변수는 명시적으로 final로 선언되어 있어야 하거나 실질적으로 final로 선언된 변수와 똑같이 사용되어야 한다.

## 질문
람다식에서는 지역 변수를 다음과 같은 상황에서 사용할 수 있습니다.
1. final로 선언되었거나
```java
final int portNumber = 1337;
Runnable r = () -> System.out.println(portNumber);
```
2. final로 선언되어있지 않아도 수정을 안하거나
```java
int portNumber = 1337;
Runnable r = () -> System.out.println(portNumber);
// portNumber = 3557; <- 주석 풀면 오류
```

그러나 수정 못하게 막을거면 첫 번째 제약만 있어도 되지 않을까 싶습니다.
수정 못하게 할꺼면서 final 아닌 변수의 사용을 허락할 필요가 있는지 의문이 듭니다.

질문을 정리하면, final 아닌 변수를 사용할 수 있게 설계한 의도에 대한 질문입니다.

**Comment by jk05018** [comment]
크으 깔끔한 설명 감사합니다!
