### ISSUE TITLE
[Chapter 5] `findAny` 가 병렬 스트림이여도 항상 같은 값을 리턴합니다.

### ISSUE THREAD

**Issue by BUYA-GH** [UMC-PNU-3rd/modern-java-in-action#9]
## 출처
출처는 따로 없습니다. 

## 질문
findAny가 일반 stream일 경우 항상 같은 결과를 보여주고,
parallelStream 일 경우 Multi Thread 로 돌아가기 때문에 
상황에 따라 다른 결과를 보여 준다고 합니다.

정말 그런지 궁금해서 제가 따로 코드를 쳐서 검사를 해봤습니다.
1. 첫번째 방법
```java
System.out.println(IntStream.range(0, 100).parallel().findAny());
```
0부터 100까지의 숫자가 있는 stream에서 아무거나 찾는 코드입니다.
제가 이 코드를 돌렸을때는 항상 65를 리턴하는 것을 보았습니다. parallel 인데도 말이죠

2. 두번째 방법
```java
        List<String> elements = Arrays.asList("a", "a1", "b", "b1", "c", "c1");

        Optional<String> anyElement = elements.stream().parallel()
                .filter(s -> s.startsWith("b")).findAny();

        System.out.println("findAny: " + anyElement.get());
```
`b` 또는 `b1` 을 결과로 반환한다고 합니다.
다만 저는 항상 `b1` 을 결과로 반환하네요.

제가 parallelStream을 잘못 사용하고 있는걸까요?
다른 분들도 한번씩 위의 코드를 실행해 결과를 공유했으면 좋겠습니다.

**Comment by whquddn55** [comment]
``` java
List<String> elements = Arrays.asList("a", "a1", "b", "b1", "c", "c1");
        List<String> res = IntStream.rangeClosed(1, 1000)
                .mapToObj(i -> {
                    Optional<String> anyElement = elements.stream().parallel()
                            .filter(s -> s.startsWith("b")).findAny();
                    return anyElement.get();
                })
                .toList();
        long bCount = res.stream()
                .filter(s -> s.equals("b"))
                .count();
        long b1Count = res.stream()
                .filter(s -> s.equals("b1"))
                .count();

        System.out.println("bCount = " + bCount + ", b1Count = " + b1Count);
```
를 돌려보면 b1이 더 많이 나오긴 하지만 b도 나오는 것 같습니다.

**Comment by seunghan0421** [comment]
https://www.popit.kr/java8-stream의-parallel-처리/

이따 같이 얘기해보시죠!

**Comment by BUYA-GH** [comment]
일단 먼저 이 질문을 하게 된 이유는 `findAny` 와 `findFirst` 의 차이점 비교였습니다.

```java
System.out.println(IntStream.range(0, 100).parallel().findAny());
```

위의 코드에서는 findFirst일 경우 1, findAny일 경우에는 65를 반환합니다.

다만 여기서 의문점이 생겼습니다. `병렬 stream을 사용한다면 run할 때 마다 findAny의 결과가 달라져야 하는게 아닌가?`
항상 

매번 다른 결과를 보고 싶으면 위의 첫 번째 comment의 코드를 사용하시면 됩니다.
그리고 왜 단순하게 parallelStream을 사용한다면 항상 같은 결과를 반환하는지는 두 번째 comment의 링크에서 보시면 됩니다.

https://www.popit.kr/java8-stream의-parallel-처리/
위의 링크를 요약하면 아래와 같습니다.

parallelStream을 사용하면 가용가능한 core 수 까지 stream을 만듭니다.(`Runtime.availableProcessors()` 까지)
그리고 stream 별로 처리해야할 data는 간단하게 반 씩 나누어 할당하는 알고리즘을 사용합니다.
이를 ForkJoin 프레임워크 라고 말하고요.

이 할당 알고리즘이 항상 같으므로 findAny의 결과도 항상 같은 것이라고 저는 결론을 내렸습니다.
답변해주신 모든 분들 다 감사합니다.
